### ISSUE TITLE
Submit to gemini software list

### ISSUE THREAD

**Issue by HAUDRAUFHAUN** [DealPete/Sputnik#17]
Sputnik isn't submitted to [this list](gemini://gemini.circumlunar.space/software/). Should I submit it there?

**Comment by DealPete** [comment]
I'm a little hesitant to submit it there because right now there isn't a way to use Gemini yet without compiling it yourself. If we uploaded a binary, would people be able to run that, or would we need to pay the >$100 for an Apple dev account so we can notarize the software?

**Comment by HAUDRAUFHAUN** [comment]
[Here](https://www.youtube.com/watch?v=Cal9l-ajWrE) is a good video about creating application installers, I think we just have to put the build app bundle into that.  Than I think GitHub releases might be a good option for uploading this installer to the web. All interested people have to do then is downloading the dmg from github and execute it for installation. 

I can't to anything advanced signing stuff or publishing apps to the app store with my account because I'm under 18 years old.

**Comment by HAUDRAUFHAUN** [comment]
I just created an installer:

[Install Sputnik.dmg.zip](https://github.com/DealPete/Sputnik/files/6439437/Install.Sputnik.dmg.zip)

## preview

https://user-images.githubusercontent.com/47633893/117407351-b53cdd80-af0e-11eb-82a1-f22ba63f43f9.mp4

**Comment by dealpete-work** [comment]
Hey, that's great. I didn't realize it was so straightforward. People will still need to do the right-click-Open trick to run it but most techy people will be used to that.

Feel free to go ahead and do a Github release.

**Comment by HAUDRAUFHAUN** [comment]
Okay, thanks for the feedback👍
